### ISSUE TITLE
如果我是aws用户，我没有权限拿ak/sk，只有iam role，应该怎么从broker load导数据？应该怎么通过外表访问存储？

### ISSUE THREAD

**Issue by MarkovWangRR** [StarRocks/docs#273]
File: [/loading/BrokerLoad.md](https://docs.starrocks.com/en-us/main/loading/BrokerLoad)

如果我是aws用户，我没有权限拿ak/sk，只有iam role，应该怎么从broker load导数据？应该怎么通过外表访问存储？

文档里没写

**Comment by evelynzhaojie** [comment]
这个应该提在中文repo里。这里是英文
