### ISSUE TITLE
[ERROR] Spelling error in data export flowchart

### ISSUE THREAD

**Issue by ss892714028** [StarRocks/docs#56]
location: https://docs.starrocks.com/en-us/main/unloading/Export
I think the phrase should be `Remote Storage` instead of `Remote Storeage`

![1648219161(1)](https://user-images.githubusercontent.com/34635663/160142293-de2fec47-9717-43e0-a311-b6d2f29ba21f.png)

**Comment by hellolilyliuyi** [comment]
Thanks for your feedbacks. 😄 The image has been revised according to your suggestion.😜
