### ISSUE TITLE
[ERROR] Grammatical error in career's page

### ISSUE THREAD

**Issue by ss892714028** [StarRocks/docs#60]
Link: https://www.starrocks.com/en-us/career

Original: Its query speed, especially multi-table join queries, far ~~exceed~~ that of other products.
Revised: Its query speed, especially multi-table join queries, far **exceeds** that of other products.

Original:  If you are not afraid to take on various roles and responsibilities, and ~~willing~~ to grow with us, this is the place for you to change the world.
Revised:  If you are not afraid to take on various roles and responsibilities, and **are willing** to grow with us, this is the place for you to change the world.

**Comment by titianqx** [comment]
done

**Comment by hellolilyliuyi** [comment]
Thanks for your feedbacks. The career's page has been revised according to your suggestion.
