### ISSUE TITLE
[ERROR] Routine load doc needs update

### ISSUE THREAD

**Issue by ss892714028** [StarRocks/docs#71]
Link to the document: https://docs.starrocks.com/en-us/main/loading/RoutineLoad#environment-requirements

Under environment requirements, 
1. StarRocks currently supports SASL authorization.
Here is the template:
```sql
CREATE ROUTINE LOAD
COLUMNS...
WHERE...
PROPERTIES (...)
FROM KAFKA
        (
        "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",
        "kafka_topic" = "my_topic",
       "property.security.protocol" = "SASL_PLAINTEXT",
        "property.sasl.mechanism" = "PLAIN",
        "property.sasl.jaas.config" = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"28.appId_110361\" password=\"xxx\"",
        "property.sasl.username" = “userxxx",
        "property.sasl.password"= "xxx"
        "property.client.id" = "my_client_id"
);
```

2. "Supported CSV text format with one line per message and no line breaks at the end."
This does not align with the Mandarin version. It supports both CSV and JSON formats. https://docs.starrocks.com/zh-cn/main/loading/RoutineLoad#environment-requirements

**Comment by jaogoy** [comment]
There are still a lot of documentation diff from 1.18 till 2.1 to be modified into English version from Mandarin version.

**Comment by ss892714028** [comment]
> There are still a lot of documentation diff from 1.18 till 2.1 to be modified into English version from Mandarin version.

Sure, I have created a PR myself.
