### ISSUE TITLE
It lacks some description about Primary Key

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs#83]
File: [/table_design/Data_model.md](https://docs.starrocks.com/en-us/main/table_design/Data_model)

Although, there is a Primary Key model section, but no description about it at the head of the article.

![image](https://user-images.githubusercontent.com/18394962/167059046-c4365c76-b56c-4b0d-bd73-5979d8be7202.png)
![Feishu20220506-105204](https://user-images.githubusercontent.com/18394962/167059115-d8f1329e-a3e5-410a-a30c-81fd0403977f.jpg)

**Comment by amber-create** [comment]
This issue has been fixed.
